[package]
name = "arena-rl"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15", features = ["dynamic_linking"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2"
rand = "0.8"

# Enable a small amount of optimization in debug mode
[profile.dev]
debug = 0
strip = "debuginfo"
opt-level = 1
split-debuginfo = "unpacked"


# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3
