#!/bin/bash
set -e

PATH_IN="assets/images/raw"
PATH_OUT="assets/images/combat"
PARAMS="filter Box -interpolate Integer"

resize () {
    # echo "mogrify -resize $1 -filter Box -path $PATH_OUT/$2 -interpolate Integer $PATH_IN/$2/*.png"
    mkdir -p "$PATH_OUT/$2"
    mogrify -resize $1 -filter Box -path $PATH_OUT/$2 -interpolate Integer $PATH_IN/$2/*.png
}

echo -n "cleaning target directory ..."
rm -rf "$PATH_OUT/**/*.png"
echo "done"


echo -n "resizing sprites..."

resize "96x96" "chars/backgrounds"
resize "96x96" "chars/bodies"
resize "96x96" "chars/equipment"
resize "96x96" "chars/fx"
resize "48x48" "chars/heads"

resize "96x96" "monster"

resize "96x96" "map"

resize "32x32" "ui/action"
resize "96x96" "ui/floor"
resize "16x16" "ui/icons"

resize "96x96"   "fx/gore"
resize "32x32"   "fx/projectiles"
resize "256x256" "fx/hit"

echo "done"

