#!/bin/bash
set -e

echo "Source directory: $1/images"

# PATH_IN="assets/images/raw"
PATH_IN=$1/images
PATH_OUT="assets/images/combat"
PARAMS="filter Box -interpolate Integer"

resize() {
  mkdir -p "$PATH_OUT/$2"
  mogrify -resize $1 -unsharp 0x1 +antialias -path $PATH_OUT/$2 $PATH_IN/$2/*.png
}

echo -n "cleaning target directory ..."
rm -rf $PATH_OUT/**/*.png
rm -rf $PATH_OUT/**/.DS_Store
echo "done"

echo -n "resizing sprites..."
mkdir -p $PATH_OUT/ui/
# cp -r $PATH_IN/ui/cards $PATH_OUT/ui/
resize "48x48" "ui/cards"

resize "128x128" "chars/bodies"
resize "128x128" "chars/equipment"
resize "128x128" "chars/fx"
resize "64x64" "chars/heads"

resize "128x128" "monster"

resize "128x128" "map"

resize "128x128" "ui/floor"

resize "128x128" "fx/gore"
resize "64x64" "fx/projectiles"
resize "256x256" "fx/hit"

echo "done"
