name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install SDL2
      run: sudo apt update && sudo apt install libsdl2-dev --fix-missing -y
    - name: Install SDL2 image
      run: sudo apt install libjpeg-dev libwebp-dev libtiff5-dev libsdl2-image-dev libsdl2-image-2.0-0 -y
    - name: Install SDL2 true type fonts
      run: sudo apt install libfreetype6-dev libsdl2-ttf-dev libsdl2-ttf-2.0 -y
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
